DROP IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL);

INSERT INTO ODONTOLOGOS VALUES(DEFAULT,223499, 'Vivas', 'Juan');