DROP IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL);

INSERT INTO ODONTOLOGOS VALUES(1, 'Vivas', 'Juan');